export const specimens = [
  {
    id: 'animal-cell',
    name: 'Animal Cell',
    description: 'A typical eukaryotic animal cell with key organelles.',
    type: 'animal',
    organelles: [
      {
        id: 'membrane',
        name: 'Cell Membrane',
        function: 'Controls what enters and exits the cell. Acts as a selective barrier.',
        size: '7-8 nm thick',
        funFact: 'The cell membrane is made of a phospholipid bilayer — essentially a double layer of fat molecules!',
        color: '#4ECDC4',
      },
      {
        id: 'nucleus',
        name: 'Nucleus',
        function: 'Contains DNA and controls cell activities. Often called the "brain" of the cell.',
        size: '5-10 μm diameter',
        funFact: 'If you stretched out all the DNA in one human cell, it would be about 2 meters long!',
        color: '#4A6CF7',
      },
      {
        id: 'mitochondria',
        name: 'Mitochondria',
        function: 'Produces ATP (energy) through cellular respiration. The powerhouse of the cell.',
        size: '1-10 μm long',
        funFact: 'Mitochondria have their own DNA and are thought to have once been independent bacteria!',
        color: '#FF8F00',
      },
      {
        id: 'er',
        name: 'Endoplasmic Reticulum',
        function: 'Rough ER makes proteins; Smooth ER makes lipids and detoxifies chemicals.',
        size: 'Network throughout cell',
        funFact: 'If you unfolded all the ER in one cell, it would cover an area larger than the cell itself!',
        color: '#9C27B0',
      },
      {
        id: 'ribosomes',
        name: 'Ribosomes',
        function: 'Assembles proteins from amino acids following mRNA instructions.',
        size: '20-30 nm',
        funFact: 'A single cell can contain up to 10 million ribosomes!',
        color: '#E91E63',
      },
      {
        id: 'golgi',
        name: 'Golgi Apparatus',
        function: 'Modifies, sorts, and packages proteins for transport or secretion.',
        size: '1-3 μm',
        funFact: 'Think of it as the cell\'s post office — it labels and ships packages to the right destination!',
        color: '#FFC107',
      },
    ],
  },
  {
    id: 'plant-cell',
    name: 'Plant Cell',
    description: 'A plant cell with unique structures like chloroplasts, cell wall, and central vacuole.',
    type: 'plant',
    organelles: [
      {
        id: 'cell-wall',
        name: 'Cell Wall',
        function: 'Provides rigid structure and protection. Made of cellulose.',
        size: '0.1-10 μm thick',
        funFact: 'Cell walls are so strong that wood is essentially billions of dead plant cell walls stacked together!',
        color: '#8D6E63',
      },
      {
        id: 'membrane',
        name: 'Cell Membrane',
        function: 'Controls what enters and exits the cell, inside the cell wall.',
        size: '7-8 nm thick',
        funFact: 'Plant cells have both a cell wall AND a cell membrane for double protection!',
        color: '#4ECDC4',
      },
      {
        id: 'nucleus',
        name: 'Nucleus',
        function: 'Contains DNA and controls cell activities.',
        size: '5-10 μm diameter',
        funFact: 'Plant nuclei contain all the instructions needed to build the entire plant!',
        color: '#4A6CF7',
      },
      {
        id: 'chloroplast',
        name: 'Chloroplast',
        function: 'Performs photosynthesis — converts sunlight into glucose (food).',
        size: '3-10 μm',
        funFact: 'Chloroplasts are why plants are green! The chlorophyll inside absorbs red and blue light, reflecting green.',
        color: '#4CAF50',
      },
      {
        id: 'vacuole',
        name: 'Central Vacuole',
        function: 'Stores water, nutrients, and waste. Maintains turgor pressure to keep the plant firm.',
        size: 'Up to 80% of cell volume',
        funFact: 'When a plant wilts, it\'s because the central vacuoles have lost water and can\'t maintain pressure!',
        color: '#81D4FA',
      },
      {
        id: 'mitochondria',
        name: 'Mitochondria',
        function: 'Produces ATP through cellular respiration, even in plants!',
        size: '1-10 μm long',
        funFact: 'Yes, plants have mitochondria too! They need cellular respiration at night when they can\'t photosynthesize.',
        color: '#FF8F00',
      },
    ],
  },
  {
    id: 'onion-root',
    name: 'Onion Root Tip',
    description: 'View cells in various stages of mitosis — prophase, metaphase, anaphase, telophase.',
    type: 'mitosis',
    organelles: [
      {
        id: 'interphase',
        name: 'Interphase Cell',
        function: 'Cell is growing and replicating DNA — preparing for division. Chromatin is dispersed.',
        size: 'Normal cell size',
        funFact: 'Cells spend about 90% of their time in interphase — it\'s the "boring" but crucial preparation phase!',
        color: '#B0BEC5',
      },
      {
        id: 'prophase',
        name: 'Prophase',
        function: 'Chromosomes condense and become visible. Nuclear envelope starts breaking down.',
        size: 'Condensing',
        funFact: 'During prophase, the chromosomes coil up so tightly they become about 10,000 times shorter!',
        color: '#4A6CF7',
      },
      {
        id: 'metaphase',
        name: 'Metaphase',
        function: 'Chromosomes line up at the cell equator. Spindle fibers attach to centromeres.',
        size: 'Aligned at center',
        funFact: 'The cell has a "checkpoint" here — if chromosomes aren\'t properly aligned, division is halted!',
        color: '#FF8F00',
      },
      {
        id: 'anaphase',
        name: 'Anaphase',
        function: 'Sister chromatids separate and move to opposite poles of the cell.',
        size: 'Moving apart',
        funFact: 'The chromosomes move at about 1 μm per minute — that\'s incredibly fast at the cellular scale!',
        color: '#E91E63',
      },
      {
        id: 'telophase',
        name: 'Telophase',
        function: 'Nuclear envelopes reform around each set of chromosomes. Cytoplasm begins dividing.',
        size: 'Two forming nuclei',
        funFact: 'By the end of telophase, one cell has become two identical daughter cells!',
        color: '#4CAF50',
      },
    ],
  },
]
